name: plant_classification
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - pandas
  - numpy
  - matplotlib
  - tensorflow
  - scipy
  - keras
  - scikit-learn
  - jupyter
  - fpdf
  - pip:
    - python-dotenv
    - mkdocs
    - pytest
    - -e .
